apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secret
  namespace: taskmanager-production
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ejJ4M2M0djU=
  MYSQL_DATABASE:      dGFza21hbmFnZXI=
  DB_PASSWORD:         ejJ4M2M0djU=
  SESSION_SECRET:      dGFza21hbmFnZXIxMjM=
